/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/songs/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve song from platform URL
         * @description Convert a platform-specific URL (Spotify, Apple Music, etc.) into a universal song with cross-platform links
         */
        post: operations["resolveSong"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search for songs across platforms
         * @description Search for songs using title, artist, album, or free-form query across multiple streaming platforms
         */
        post: operations["searchSongs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{songId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get song by ID or ISRC
         * @description Retrieve a song by its database ID or ISRC code
         */
        get: operations["getSong"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/s/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Universal song link redirect
         * @description Universal link endpoint that redirects to song page or returns JSON based on Accept header
         */
        get: operations["universalSongLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get supported platforms
         * @description List all supported streaming platforms and their configuration
         */
        get: operations["getPlatforms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Check API health and service status
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ResolveSongRequest: {
            /**
             * Format: uri
             * @description Platform-specific song URL
             * @example https://open.spotify.com/track/4u7EnebtmKWzUH433cf5Qv
             */
            url: string;
        };
        SearchSongsRequest: {
            /**
             * @description Song title
             * @example Bohemian Rhapsody
             */
            title?: string;
            /**
             * @description Artist name
             * @example Queen
             */
            artist?: string;
            /**
             * @description Album name
             * @example A Night at the Opera
             */
            album?: string;
            /**
             * @description Free-form search query
             * @example Bohemian Rhapsody Queen
             */
            query?: string;
            /**
             * @description Specific platform to search (optional)
             * @example spotify
             * @enum {string}
             */
            platform?: "spotify" | "apple_music" | "tidal" | "youtube_music" | "deezer";
            /**
             * @description Maximum results per platform
             * @default 10
             * @example 10
             */
            limit: number;
        } | unknown | unknown | unknown;
        ResolveSongResponse: {
            song: components["schemas"]["SongMetadata"];
            /**
             * @description Platform-specific links
             * @example {
             *       "spotify": {
             *         "url": "https://open.spotify.com/track/4u7EnebtmKWzUH433cf5Qv",
             *         "available": true,
             *         "platform": "spotify",
             *         "confidence": 0.98
             *       },
             *       "apple_music": {
             *         "url": "https://music.apple.com/us/album/bohemian-rhapsody/1440650428?i=1440650439",
             *         "available": true,
             *         "platform": "apple_music",
             *         "confidence": 0.95
             *       }
             *     }
             */
            platforms: {
                [key: string]: components["schemas"]["PlatformLink"];
            };
            /**
             * Format: uri
             * @description Universal SongShare link
             * @example https://songshare.dev/s/GBUM71505078
             */
            universal_link: string;
        };
        SearchSongsResponse: {
            /**
             * @description Search results grouped by platform
             * @example {
             *       "spotify": [
             *         {
             *           "title": "Bohemian Rhapsody",
             *           "artists": [
             *             "Queen"
             *           ],
             *           "album": "A Night at the Opera",
             *           "url": "https://open.spotify.com/track/4u7EnebtmKWzUH433cf5Qv",
             *           "platform": "spotify",
             *           "isrc": "GBUM71505078",
             *           "duration_ms": 355000,
             *           "available": true
             *         }
             *       ],
             *       "apple_music": [
             *         {
             *           "title": "Bohemian Rhapsody",
             *           "artists": [
             *             "Queen"
             *           ],
             *           "album": "A Night at the Opera",
             *           "url": "https://music.apple.com/us/album/bohemian-rhapsody/1440650428?i=1440650439",
             *           "platform": "apple_music",
             *           "isrc": "GBUM71505078",
             *           "duration_ms": 355000,
             *           "available": true
             *         }
             *       ]
             *     }
             */
            results: {
                [key: string]: components["schemas"]["SearchResult"][];
            };
            query: components["schemas"]["SearchSongsRequest"];
            /**
             * @description Total number of results across all platforms
             * @example 15
             */
            total_results?: number;
        };
        Song: {
            /**
             * @description Unique song identifier
             * @example 507f1f77bcf86cd799439011
             */
            id: string;
            /**
             * @description Song title
             * @example Bohemian Rhapsody
             */
            title: string;
            /**
             * @description Primary artist name
             * @example Queen
             */
            artist: string;
            /**
             * @description Album name
             * @example A Night at the Opera
             */
            album?: string;
            /**
             * @description Duration in seconds
             * @example 355
             */
            duration?: number;
            /**
             * @description International Standard Recording Code
             * @example GBUM71505078
             */
            isrc?: string;
            /**
             * Format: uri
             * @description Album artwork URL
             * @example https://i.scdn.co/image/ab67616d0000b273ce4f1737bc8a646c8c4bd25a
             */
            album_art?: string;
            /** @description Available platform links */
            platforms: components["schemas"]["PlatformLink"][];
            /**
             * Format: date-time
             * @description When the song was first added
             * @example 2024-01-15T10:30:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When the song was last updated
             * @example 2024-01-15T10:30:00Z
             */
            updated_at: string;
        };
        SongMetadata: {
            /**
             * @description Unique song identifier
             * @example 507f1f77bcf86cd799439011
             */
            id: string;
            /**
             * @description Song title
             * @example Bohemian Rhapsody
             */
            title: string;
            /**
             * @description List of artists
             * @example [
             *       "Queen"
             *     ]
             */
            artists: string[];
            /**
             * @description Album name
             * @example A Night at the Opera
             */
            album?: string;
            /**
             * @description Duration in milliseconds
             * @example 355000
             */
            duration_ms?: number;
            /**
             * Format: date
             * @description Release date
             * @example 1975-10-31
             */
            release_date?: string;
            /**
             * @description International Standard Recording Code
             * @example GBUM71505078
             */
            isrc?: string;
            /**
             * Format: uri
             * @description Album artwork URL
             * @example https://i.scdn.co/image/ab67616d0000b273ce4f1737bc8a646c8c4bd25a
             */
            image_url?: string;
        };
        PlatformLink: {
            /**
             * @description Streaming platform identifier
             * @example spotify
             * @enum {string}
             */
            platform: "spotify" | "apple_music" | "tidal" | "youtube_music" | "deezer";
            /**
             * Format: uri
             * @description Platform-specific song URL
             * @example https://open.spotify.com/track/4u7EnebtmKWzUH433cf5Qv
             */
            url: string;
            /**
             * @description Whether the song is currently available on this platform
             * @example true
             */
            available: boolean;
            /**
             * Format: float
             * @description Match confidence score (0-1)
             * @example 0.98
             */
            confidence: number;
        };
        SearchResult: {
            /**
             * @description Song title
             * @example Bohemian Rhapsody
             */
            title: string;
            /**
             * @description List of artists
             * @example [
             *       "Queen"
             *     ]
             */
            artists: string[];
            /**
             * @description Album name
             * @example A Night at the Opera
             */
            album?: string;
            /**
             * Format: uri
             * @description Platform-specific song URL
             * @example https://open.spotify.com/track/4u7EnebtmKWzUH433cf5Qv
             */
            url: string;
            /**
             * @description Platform identifier
             * @example spotify
             * @enum {string}
             */
            platform: "spotify" | "apple_music" | "tidal" | "youtube_music" | "deezer" | "local";
            /**
             * @description International Standard Recording Code
             * @example GBUM71505078
             */
            isrc?: string;
            /**
             * @description Duration in milliseconds
             * @example 355000
             */
            duration_ms?: number;
            /**
             * Format: date
             * @description Release date
             * @example 1975-10-31
             */
            release_date?: string;
            /**
             * Format: uri
             * @description Album artwork URL
             * @example https://i.scdn.co/image/ab67616d0000b273ce4f1737bc8a646c8c4bd25a
             */
            image_url?: string;
            /**
             * @description Platform-specific popularity score
             * @example 85
             */
            popularity?: number;
            /**
             * @description Whether the song contains explicit content
             * @example false
             */
            explicit?: boolean;
            /**
             * @description Whether the song is currently available
             * @example true
             */
            available: boolean;
        };
        PlatformsResponse: {
            platforms: components["schemas"]["Platform"][];
        };
        Platform: {
            /**
             * @description Platform identifier
             * @example spotify
             * @enum {string}
             */
            id: "spotify" | "apple_music" | "tidal" | "youtube_music" | "deezer";
            /**
             * @description Human-readable platform name
             * @example Spotify
             */
            name: string;
            /**
             * @description Whether this platform is currently supported
             * @example true
             */
            supported: boolean;
            /**
             * Format: uri
             * @description Platform icon URL
             * @example https://cdn.songshare.dev/icons/spotify.svg
             */
            icon_url?: string;
            /**
             * @description Platform brand color (hex)
             * @example #1DB954
             */
            color?: string;
        };
        HealthResponse: {
            /**
             * @description Overall service health
             * @example healthy
             * @enum {string}
             */
            status: "healthy" | "degraded" | "unhealthy";
            /**
             * Format: date-time
             * @description Health check timestamp
             * @example 2024-01-15T10:30:00Z
             */
            timestamp: string;
            services?: {
                /**
                 * @example healthy
                 * @enum {string}
                 */
                database?: "healthy" | "unhealthy";
                /**
                 * @example healthy
                 * @enum {string}
                 */
                spotify?: "healthy" | "unhealthy";
                /**
                 * @example healthy
                 * @enum {string}
                 */
                apple_music?: "healthy" | "unhealthy";
                /**
                 * @example healthy
                 * @enum {string}
                 */
                tidal?: "healthy" | "unhealthy";
            };
        };
        Error: {
            /**
             * @description Error message
             * @example Invalid request body
             */
            error: string;
            /**
             * @description Additional error details
             * @example Missing required field: url
             */
            details?: string;
            /**
             * @description Error code for programmatic handling
             * @example VALIDATION_ERROR
             */
            code?: string;
        };
    };
    responses: {
        /** @description Bad request - invalid input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /** @example {
                 *       "error": "Invalid request body",
                 *       "details": "Missing required field: url",
                 *       "code": "VALIDATION_ERROR"
                 *     } */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /** @example {
                 *       "error": "Song not found",
                 *       "details": "No song found with identifier: GBUM71505078",
                 *       "code": "NOT_FOUND"
                 *     } */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /** @example {
                 *       "error": "Internal server error",
                 *       "details": "Database connection failed",
                 *       "code": "INTERNAL_ERROR"
                 *     } */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resolveSong: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveSongRequest"];
            };
        };
        responses: {
            /** @description Song successfully resolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveSongResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    searchSongs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchSongsRequest"];
            };
        };
        responses: {
            /** @description Search results from platforms */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSongsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getSong: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Song database ID or ISRC code */
                songId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Song details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Song"];
                    /** @description HTML page for browser requests */
                    "text/html": string;
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    universalSongLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ISRC code or song identifier
                 * @example GBUM71505078
                 */
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Song page or JSON response based on Accept header */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Song"];
                    /** @description HTML song page */
                    "text/html": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPlatforms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of supported platforms */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformsResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
