// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
/**
 * This file was automatically generated by tygo.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * To regenerate: run `tygo generate` or `make types`
 */

//////////
// source: song.go

export interface Song {
  id: string;
  isrc: string;
  title: string;
  artists: string[];
  album: string;
  albumArt: string;
  duration: number /* int */; // milliseconds
  releaseDate: string;
  explicit: boolean;
  platforms: PlatformLink[];
  createdAt: string;
  updatedAt: string;
}
export interface PlatformLink {
  platform: string; // "spotify", "apple_music"
  id: string;
  url: string;
}
/**
 * SearchRequest represents a text search query
 */
export interface SearchRequest {
  query: string;
  offset: number /* int */; // Number of results to skip (for pagination)
  limit: number /* int */; // Number of results to return (default 10)
}
/**
 * ResolveRequest represents a platform URL to resolve
 */
export interface ResolveRequest {
  url: string;
}
/**
 * Platform represents a supported music platform
 */
export interface Platform {
  id: string;
  name: string;
}
